//Laboratorio 1

// 1. Obtener todos los registros de una tabla
GET http://localhost:5050/products

// 2. Filtrar por una condición simple
GET http://localhost:5050/products-lower-one


//3. Seleccionar campos específicos
GET http://localhost:5050/users

//4. Ordenar resultados por una columna
GET http://localhost:5050/orders


